name: Int Scan

on:
  pull_request:
    types: [opened]
  workflow_dispatch :
env :
  API_URL : "https://int.api.zscwp.io"
  AUTH_URL : "https://int-auth.zscwp.io"
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses : ZscalerCWP/Zscaler-IaC-Action@main
        id : iac-scan
        with:
          client_id : ${{ secrets.ZSCANNER_INT_CLIENTID }}
          client_secret : ${{ secrets.ZSCANNER_INT_SECRET }}
          fail_build : 'true'
          region : 'CUSTOM'
          output_format : 'human+github-sarif'
          log_level : 'debug'
      - run : echo ${{ steps.iac-scan.outputs.sarif_file_path }}
      - name: Upload SARIF file
        if: ${{ success() || failure() && (steps.iac-scan.outputs.sarif_file_path != '') }}
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.iac-scan.outputs.sarif_file_path }}
